export const styleKey = [
{value:"height", desc:"高度"},
{value:"width", desc:"宽度"},
{value:"background-color", desc:"背景色"},
{value:"border", desc:"边框"},
{value:"border-left", desc:"左边框"},
{value:"border-right", desc:"右边框"},
{value:"border-top", desc:"上边框"},
{value:"border-bottom", desc:"下边框"},
{value:"margin", desc:"外边距"},
{value:"margin-left", desc:"左外边距"},
{value:"margin-right", desc:"右外边距"},
{value:"margin-top", desc:"上外边距"},
{value:"margin-bottom", desc:"下外边距"},
{value:"padding", desc:"内边距"},
{value:"padding-left", desc:"左内边距"},
{value:"padding-right", desc:"右内边距"},
{value:"padding-top", desc:"上内边距"},
{value:"padding-bottom", desc:"下内边距"},
{value:"font-size", desc:"字体大小"},
{value:"color", desc:"字体颜色"},
{value:"display", desc:"显示类型"},
{value:"text-align", desc:"文本排列方式"},
];

export default styleKey;
